<a href="https://colab.research.google.com/github/AnusreePutta/Info-5731/blob/main/Putta_Anusree_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INFO5731 In-class Exercise 3**

The purpose of this exercise is to explore various aspects of text analysis, including feature extraction, feature selection, and text similarity ranking.

**Expectations**:
*   Students are expected to complete the exercise during lecture period to meet the active participation criteria of the course.
*   Use the provided .*ipynb* document to write your code & respond to the questions. Avoid generating a new file.
*   Write complete answers and run all the cells before submission.
*   Make sure the submission is "clean"; *i.e.*, no unnecessary code cells.
*   Once finished, allow shared rights from top right corner (*see Canvas for details*).

**Total points**: 40

**Deadline**: This in-class exercise is due at the end of the day tomorrow, at 11:59 PM.

**Late submissions will have a penalty of 10% of the marks for each day of late submission. , and no requests will be answered. Manage your time accordingly.**


## Question 1 (10 Points)
Describe an interesting text classification or text mining task and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features.

In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:


I am considering sentimental analysis for this answer.sentimental analysis on social media comments to say wheather comments are positive,negative or neutral.
The 5 points which I considered are:

1.Bag-of-words:
Explanation: BoW is a measure of a word's frequency in a document that takes its occurrence into account rather than its order. This sums up the entire vocabulary that was used in the comment.
Usefulness: The frequency of words might aid the model in identifying sentiment patterns, as certain phrases may be linked to different sentiments.

2.Term Frequency-Inverse Document Frequency, or TF-IDF:

To put it another way, TF-IDF is a statistical metric that assesses a word's significance in a document in relation to a corpus of documents.
Usefulness: Words that appear frequently in a particular comment but infrequently in the corpus as a whole may reflect sentiment. Words that are strongly connected to either happiness or negativity, for instance.

3.Analysis of Emotions:

Explanation: Examining verbally expressed emotions like happiness, rage, grief, etc.
Usefulness: Specific sentiments are linked to particular emotions. For example, happy feelings frequently involve happiness, whereas negative feelings could involve despair or wrath.

4.Tags for Part-of-Speech (POS):

Explaination: Determining which grammatical category—nouns, verbs, adjectives, etc.—each word belongs in.
Usefulness: Sentences' syntactic composition can be understood by looking at the grammatical structure, which can help reveal sentiment's complexities and nuances.

N-grams:

Definition: A document's sequence of 'n' adjacent words, where 'n' can be one, two, three, or more.
Contextual information is captured, which aids in comprehending the meaning of words in relation to their neighbors. Bigrams or trigrams, for instance, may capture particular words that express emotion.



'''

## Question 2 (10 Points)
Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [67]:

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.sentiment import SentimentIntensityAnalyzer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
!pip install vaderSentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
!python -m nltk.downloader averaged_perceptron_tagger

# Sample dataset
reviews = [
    ("Positive review", "This product is excellent, and I am satisfied with my purchase."),
    ("Negative review", "The quality of the product is disappointing, and I regret buying it."),
    ("Neutral review", "The product is okay, not too bad but not outstanding either.")
]

# Extracting features
labels, texts = zip(*reviews)

# Bag-of-Words (BoW)
vectorizer_bow = CountVectorizer()
bow_matrix = vectorizer_bow.fit_transform(texts)
print("\nBag-of-Words (BoW):")
print(vectorizer_bow.get_feature_names_out())
print(bow_matrix.toarray())

# TF-IDF
vectorizer_tfidf = TfidfVectorizer()
tfidf_matrix = vectorizer_tfidf.fit_transform(texts)
print("\nTF-IDF:")
print(vectorizer_tfidf.get_feature_names_out())
print(tfidf_matrix.toarray())

# Sentiment Analysis
sia = SentimentIntensityAnalyzer()
sentiments = [sia.polarity_scores(text) for text in texts]
print("\nSentiment Analysis:")
print(sentiments)

# POS Tags
pos_tags = [nltk.pos_tag(word_tokenize(text.lower())) for text in texts]
print("\nPart-of-Speech (POS) Tags:")
print(pos_tags)

# N-grams
n_grams_vectorizer = CountVectorizer(ngram_range=(1, 2))
n_grams_matrix = n_grams_vectorizer.fit_transform(texts)
print("\nN-grams:")
print(n_grams_vectorizer.get_feature_names_out())
print(n_grams_matrix.toarray())


/usr/lib/python3.10/runpy.py:126: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

Bag-of-Words (BoW):
['am' 'and' 'bad' 'but' 'buying' 'disappointing' 'either' 'excellent' 'is'
 'it' 'my' 'not' 'of' 'okay' 'outstanding' 'product' 'purchase' 'quality'
 'regret' 'satisfied' 'the' 'this' 'too' 'with']
[[1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 0 0 1 0 1 0 1]
 [0 1 0 0 1 1 0 0 1 1 0 0 1 0 0 1 0 1 1 0 2 0 0 0]
 [0 0 1 1 0 0 1 0 1 0 0 2 0 1 1 1 0 0 0 0 1 0 1 0]]

TF-IDF:
['am' 'and' 'bad' 'but' 'buying' 'disappointing' 'either' 'excellent' 'is'
 'it' 'my' 'not' 'of' 'okay' 'outstanding' 'product' 'purchase' 'quality'
 'regret' 'satisfied' 'the' 'this' 'too' 'wi

## Question 3 (10 points):
Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)."

Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [65]:
!pip install numpy

In [66]:
import numpy as np

In [64]:
import torch
from transformers import AutoTokenizer, AutoModel
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
!pip install torchmetrics
import torchmetrics
from torchmetrics.functional import cosine_similarity
# Sample text data
text_data = [
    "As part of Meta’s commitment to open science, today we are publicly releasing LLaMA (Large Language Model Meta AI)",
    "a state-of-the-art foundational large language model designed to help researchers advance their work in this subfield of AI.",
    "Smaller, more performant models such as LLaMA enable others in the research community who don’t have access to large amounts of infrastructure to study these models",
    "further democratizing access in this important, fast-changing field.",
    "Training smaller foundation models like LLaMA is desirable in the large language model space because it requires far less computing power and resources to test new approaches",
    "Validate others’ work, and explore new use cases. Foundation models train on a large set of unlabeled data, which makes them ideal for fine-tuning for a variety of tasks",
    "We are making LLaMA available at several sizes (7B, 13B, 33B, and 65B parameters) and also sharing a LLaMA model card that details how we built the model in keeping with our approach to Responsible AI practices.",
    "Making it an avant-garde platform for pioneering new prompting strategies This research aims to bridge the gap between LLM reasoning and human thought processes, mirroring the intricate networks observed in phenomena like brain mechanisms and recurrence.",
]

# Query
query = "I'm looking for a reliable Llama model for text summarization."

# Load pre-trained BERT model and tokenizer
model_name = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

# Tokenize and encode the query
query_tokens = tokenizer(query, padding=True, truncation=True, return_tensors="pt")
with torch.no_grad():
   query_output = model(**tokenizer(query, padding=True, truncation=True, return_tensors="pt")).last_hidden_state.mean(dim=1)
# Calculate cosine similarity between the query and each review
# Calculate cosine similarity between the query and each review
similarities = [cosine_similarity(query_output.detach(), model(**tokenizer(review, padding=True, truncation=True, return_tensors="pt")).last_hidden_state.mean(dim=1)).item() for review in text_data]
# Rank the reviews based on similarity in descending order
ranked_reviews = sorted(zip(text_data, similarities), key=lambda x: x[1], reverse=True)

# Print the ranked reviews
for i, (review, similarity) in enumerate(ranked_reviews, start=1):
    print(f"Rank {i}: Similarity = {similarity:.4f}\nReview: {review}\n")


Rank 1: Similarity = 0.7423
Review: We are making LLaMA available at several sizes (7B, 13B, 33B, and 65B parameters) and also sharing a LLaMA model card that details how we built the model in keeping with our approach to Responsible AI practices.

Rank 2: Similarity = 0.7376
Review: Validate others’ work, and explore new use cases. Foundation models train on a large set of unlabeled data, which makes them ideal for fine-tuning for a variety of tasks

Rank 3: Similarity = 0.7193
Review: Training smaller foundation models like LLaMA is desirable in the large language model space because it requires far less computing power and resources to test new approaches

Rank 4: Similarity = 0.7073
Review: As part of Meta’s commitment to open science, today we are publicly releasing LLaMA (Large Language Model Meta AI)

Rank 5: Similarity = 0.6945
Review: Smaller, more performant models such as LLaMA enable others in the research community who don’t have access to large amounts of infrastructure t

# Mandatory Question

**Important: Reflective Feedback on this exercise**

Please provide your thoughts and feedback on the exercises you completed in this assignment. Consider the following points in your response:

Learning Experience: Describe your overall learning experience in working on extracting features from text data. What were the key concepts or techniques you found most beneficial in understanding the process?

Challenges Encountered: Were there specific difficulties in completing this exercise?

Relevance to Your Field of Study: How does this exercise relate to the field of NLP?

**(Your submission will not be graded if this question is left unanswered)**



Learning Experience: I learned a lot from working on the text data extraction and feature engineering assignments. Tokenization, different feature extraction techniques like Bag-of-Words and TF-IDF, and sophisticated approaches like Word Embeddings (Word2Vec), Topic Modeling (LDA), Named Entity Recognition (NER), and Sentiment Analysis are some of the important ideas that stood out. For NLP tasks, it is essential to know how to preprocess text data and extract relevant features.

Challenges Faced: Although the exercises addressed a wide range of features and strategies, the code snippets' simplification for clarity may provide a challenge. In real-world applications, the choice of parameters, model fine-tuning, and managing larger datasets might create extra complications. Additionally, using cutting-edge models like BERT may necessitate some experience with deep